import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Sidebar } from '@/components/sidebar'
import { FollowBar } from '@/components/follow-bar'
import { getServerSession } from 'next-auth'
import { ModalProvider } from '@/provider/modal-provider'
import { ThemeProvider } from '@/provider/theme-provider'
import SessionProvider from '@/provider/session-provider'
import { ToastProvider } from '@/provider/toast-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()

  return (
    <html lang='en'>
      <body className={inter.className}>
        <SessionProvider session={session}>
          <ThemeProvider
            attribute='class'
            defaultTheme='dark'
            enableSystem
            disableTransitionOnChange
          >
            <div className='h-screen'>
              <div className='container h-full mx-auto xl:px-30 max-w-6xl'>
                <div className='grid grid-cols-4 h-full'>
                  <Sidebar />
                  <div className='col-span-3 lg:col-span-2 border-x-[1px] border-neutral-800'>
                    <ModalProvider />
                    <ToastProvider />
                    {children}
                  </div>
                  <FollowBar />
                </div>
              </div>
            </div>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
